<a href="https://colab.research.google.com/github/rtosta/python_analise_dados/blob/main/notebooks/An%C3%A1lise_dados_7_operadores_de_compara%C3%A7%C3%A3o_e_l%C3%B3gicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
#seleção (filtragem de linhas específicas de um dataframe)
dataframe_01=pd.DataFrame({
    "região":["america do sul", "america do sul", "america do sul", "america do sul","africa","asia"],
    "estados":["brasil","argentina","uruguai","paraguai","angola","timor leste"],
    "idh":[0.754,0.842,0.809,0.724,0.574, 0.607]
                           })
dataframe_01

           região      estados    idh
0  america do sul       brasil  0.754
1  america do sul    argentina  0.842
2  america do sul      uruguai  0.809
3  america do sul     paraguai  0.724
4          africa       angola  0.574
5            asia  timor leste  0.607

In [3]:
região=dataframe_01["região"]=="asia"
região

0    False
1    False
2    False
3    False
4    False
5     True
Name: região, dtype: bool

In [4]:
dataframe_01[região]

  região      estados    idh
5   asia  timor leste  0.607

In [5]:
região=dataframe_01[dataframe_01["região"]=="asia"]
região

  região      estados    idh
5   asia  timor leste  0.607

In [6]:
busca=dataframe_01["região"]=="africa"
dataframe_01[busca]

   região estados    idh
4  africa  angola  0.574

In [7]:
busca=dataframe_01["idh"]<=0.574
dataframe_01[busca]

   região estados    idh
4  africa  angola  0.574

In [8]:
dataframe_01

           região      estados    idh
0  america do sul       brasil  0.754
1  america do sul    argentina  0.842
2  america do sul      uruguai  0.809
3  america do sul     paraguai  0.724
4          africa       angola  0.574
5            asia  timor leste  0.607

In [9]:
#& (and); | (or); & ~ (not)
busca=(dataframe_01["região"]=="africa") & ~(dataframe_01["idh"]>1)
busca

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [10]:
resultado=dataframe_01[busca]
resultado

   região estados    idh
4  africa  angola  0.574